// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// VulnerabilitiesColumns holds the columns for the "vulnerabilities" table.
	VulnerabilitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "summary", Type: field.TypeString},
		{Name: "cveid", Type: field.TypeString},
		{Name: "published_date", Type: field.TypeString},
		{Name: "last_modified", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "nvd_score", Type: field.TypeString},
		{Name: "cna_score", Type: field.TypeString},
		{Name: "affected_versions", Type: field.TypeString},
		{Name: "patched_versions", Type: field.TypeString},
		{Name: "severity", Type: field.TypeString},
		{Name: "pipline_id", Type: field.TypeString},
	}
	// VulnerabilitiesTable holds the schema information for the "vulnerabilities" table.
	VulnerabilitiesTable = &schema.Table{
		Name:       "vulnerabilities",
		Columns:    VulnerabilitiesColumns,
		PrimaryKey: []*schema.Column{VulnerabilitiesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VulnerabilitiesTable,
	}
)

func init() {
}
