// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: grpc/scrapper.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScrapperServiceClient is the client API for ScrapperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScrapperServiceClient interface {
	FetchVulnerabilities(ctx context.Context, in *VulnerabilityRequest, opts ...grpc.CallOption) (*VulnerabilityResponse, error)
}

type scrapperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapperServiceClient(cc grpc.ClientConnInterface) ScrapperServiceClient {
	return &scrapperServiceClient{cc}
}

func (c *scrapperServiceClient) FetchVulnerabilities(ctx context.Context, in *VulnerabilityRequest, opts ...grpc.CallOption) (*VulnerabilityResponse, error) {
	out := new(VulnerabilityResponse)
	err := c.cc.Invoke(ctx, "/grpc.ScrapperService/FetchVulnerabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapperServiceServer is the server API for ScrapperService service.
// All implementations must embed UnimplementedScrapperServiceServer
// for forward compatibility
type ScrapperServiceServer interface {
	FetchVulnerabilities(context.Context, *VulnerabilityRequest) (*VulnerabilityResponse, error)
	mustEmbedUnimplementedScrapperServiceServer()
}

// UnimplementedScrapperServiceServer must be embedded to have forward compatible implementations.
type UnimplementedScrapperServiceServer struct {
}

func (UnimplementedScrapperServiceServer) FetchVulnerabilities(context.Context, *VulnerabilityRequest) (*VulnerabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchVulnerabilities not implemented")
}
func (UnimplementedScrapperServiceServer) mustEmbedUnimplementedScrapperServiceServer() {}

// UnsafeScrapperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScrapperServiceServer will
// result in compilation errors.
type UnsafeScrapperServiceServer interface {
	mustEmbedUnimplementedScrapperServiceServer()
}

func RegisterScrapperServiceServer(s grpc.ServiceRegistrar, srv ScrapperServiceServer) {
	s.RegisterService(&ScrapperService_ServiceDesc, srv)
}

func _ScrapperService_FetchVulnerabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VulnerabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapperServiceServer).FetchVulnerabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.ScrapperService/FetchVulnerabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapperServiceServer).FetchVulnerabilities(ctx, req.(*VulnerabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScrapperService_ServiceDesc is the grpc.ServiceDesc for ScrapperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScrapperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ScrapperService",
	HandlerType: (*ScrapperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchVulnerabilities",
			Handler:    _ScrapperService_FetchVulnerabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/scrapper.proto",
}
