// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"khazande/ent/predicate"
	"khazande/ent/vulnerability"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeVulnerability = "Vulnerability"
)

// VulnerabilityMutation represents an operation that mutates the Vulnerability nodes in the graph.
type VulnerabilityMutation struct {
	config
	op                Op
	typ               string
	id                *int
	name              *string
	summary           *string
	_CVEID            *string
	published_date    *string
	last_modified     *string
	description       *string
	_NVD_score        *string
	_CNA_score        *string
	affected_versions *string
	patched_versions  *string
	severity          *string
	pipline_id        *string
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*Vulnerability, error)
	predicates        []predicate.Vulnerability
}

var _ ent.Mutation = (*VulnerabilityMutation)(nil)

// vulnerabilityOption allows management of the mutation configuration using functional options.
type vulnerabilityOption func(*VulnerabilityMutation)

// newVulnerabilityMutation creates new mutation for the Vulnerability entity.
func newVulnerabilityMutation(c config, op Op, opts ...vulnerabilityOption) *VulnerabilityMutation {
	m := &VulnerabilityMutation{
		config:        c,
		op:            op,
		typ:           TypeVulnerability,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withVulnerabilityID sets the ID field of the mutation.
func withVulnerabilityID(id int) vulnerabilityOption {
	return func(m *VulnerabilityMutation) {
		var (
			err   error
			once  sync.Once
			value *Vulnerability
		)
		m.oldValue = func(ctx context.Context) (*Vulnerability, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Vulnerability.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withVulnerability sets the old Vulnerability of the mutation.
func withVulnerability(node *Vulnerability) vulnerabilityOption {
	return func(m *VulnerabilityMutation) {
		m.oldValue = func(context.Context) (*Vulnerability, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m VulnerabilityMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m VulnerabilityMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *VulnerabilityMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *VulnerabilityMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Vulnerability.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *VulnerabilityMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *VulnerabilityMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *VulnerabilityMutation) ResetName() {
	m.name = nil
}

// SetSummary sets the "summary" field.
func (m *VulnerabilityMutation) SetSummary(s string) {
	m.summary = &s
}

// Summary returns the value of the "summary" field in the mutation.
func (m *VulnerabilityMutation) Summary() (r string, exists bool) {
	v := m.summary
	if v == nil {
		return
	}
	return *v, true
}

// OldSummary returns the old "summary" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldSummary(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSummary is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSummary requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSummary: %w", err)
	}
	return oldValue.Summary, nil
}

// ResetSummary resets all changes to the "summary" field.
func (m *VulnerabilityMutation) ResetSummary() {
	m.summary = nil
}

// SetCVEID sets the "CVEID" field.
func (m *VulnerabilityMutation) SetCVEID(s string) {
	m._CVEID = &s
}

// CVEID returns the value of the "CVEID" field in the mutation.
func (m *VulnerabilityMutation) CVEID() (r string, exists bool) {
	v := m._CVEID
	if v == nil {
		return
	}
	return *v, true
}

// OldCVEID returns the old "CVEID" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldCVEID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCVEID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCVEID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCVEID: %w", err)
	}
	return oldValue.CVEID, nil
}

// ResetCVEID resets all changes to the "CVEID" field.
func (m *VulnerabilityMutation) ResetCVEID() {
	m._CVEID = nil
}

// SetPublishedDate sets the "published_date" field.
func (m *VulnerabilityMutation) SetPublishedDate(s string) {
	m.published_date = &s
}

// PublishedDate returns the value of the "published_date" field in the mutation.
func (m *VulnerabilityMutation) PublishedDate() (r string, exists bool) {
	v := m.published_date
	if v == nil {
		return
	}
	return *v, true
}

// OldPublishedDate returns the old "published_date" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldPublishedDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublishedDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublishedDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublishedDate: %w", err)
	}
	return oldValue.PublishedDate, nil
}

// ResetPublishedDate resets all changes to the "published_date" field.
func (m *VulnerabilityMutation) ResetPublishedDate() {
	m.published_date = nil
}

// SetLastModified sets the "last_modified" field.
func (m *VulnerabilityMutation) SetLastModified(s string) {
	m.last_modified = &s
}

// LastModified returns the value of the "last_modified" field in the mutation.
func (m *VulnerabilityMutation) LastModified() (r string, exists bool) {
	v := m.last_modified
	if v == nil {
		return
	}
	return *v, true
}

// OldLastModified returns the old "last_modified" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldLastModified(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastModified is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastModified requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastModified: %w", err)
	}
	return oldValue.LastModified, nil
}

// ResetLastModified resets all changes to the "last_modified" field.
func (m *VulnerabilityMutation) ResetLastModified() {
	m.last_modified = nil
}

// SetDescription sets the "description" field.
func (m *VulnerabilityMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *VulnerabilityMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ResetDescription resets all changes to the "description" field.
func (m *VulnerabilityMutation) ResetDescription() {
	m.description = nil
}

// SetNVDScore sets the "NVD_score" field.
func (m *VulnerabilityMutation) SetNVDScore(s string) {
	m._NVD_score = &s
}

// NVDScore returns the value of the "NVD_score" field in the mutation.
func (m *VulnerabilityMutation) NVDScore() (r string, exists bool) {
	v := m._NVD_score
	if v == nil {
		return
	}
	return *v, true
}

// OldNVDScore returns the old "NVD_score" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldNVDScore(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNVDScore is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNVDScore requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNVDScore: %w", err)
	}
	return oldValue.NVDScore, nil
}

// ResetNVDScore resets all changes to the "NVD_score" field.
func (m *VulnerabilityMutation) ResetNVDScore() {
	m._NVD_score = nil
}

// SetCNAScore sets the "CNA_score" field.
func (m *VulnerabilityMutation) SetCNAScore(s string) {
	m._CNA_score = &s
}

// CNAScore returns the value of the "CNA_score" field in the mutation.
func (m *VulnerabilityMutation) CNAScore() (r string, exists bool) {
	v := m._CNA_score
	if v == nil {
		return
	}
	return *v, true
}

// OldCNAScore returns the old "CNA_score" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldCNAScore(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCNAScore is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCNAScore requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCNAScore: %w", err)
	}
	return oldValue.CNAScore, nil
}

// ResetCNAScore resets all changes to the "CNA_score" field.
func (m *VulnerabilityMutation) ResetCNAScore() {
	m._CNA_score = nil
}

// SetAffectedVersions sets the "affected_versions" field.
func (m *VulnerabilityMutation) SetAffectedVersions(s string) {
	m.affected_versions = &s
}

// AffectedVersions returns the value of the "affected_versions" field in the mutation.
func (m *VulnerabilityMutation) AffectedVersions() (r string, exists bool) {
	v := m.affected_versions
	if v == nil {
		return
	}
	return *v, true
}

// OldAffectedVersions returns the old "affected_versions" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldAffectedVersions(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAffectedVersions is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAffectedVersions requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAffectedVersions: %w", err)
	}
	return oldValue.AffectedVersions, nil
}

// ResetAffectedVersions resets all changes to the "affected_versions" field.
func (m *VulnerabilityMutation) ResetAffectedVersions() {
	m.affected_versions = nil
}

// SetPatchedVersions sets the "patched_versions" field.
func (m *VulnerabilityMutation) SetPatchedVersions(s string) {
	m.patched_versions = &s
}

// PatchedVersions returns the value of the "patched_versions" field in the mutation.
func (m *VulnerabilityMutation) PatchedVersions() (r string, exists bool) {
	v := m.patched_versions
	if v == nil {
		return
	}
	return *v, true
}

// OldPatchedVersions returns the old "patched_versions" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldPatchedVersions(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPatchedVersions is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPatchedVersions requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPatchedVersions: %w", err)
	}
	return oldValue.PatchedVersions, nil
}

// ResetPatchedVersions resets all changes to the "patched_versions" field.
func (m *VulnerabilityMutation) ResetPatchedVersions() {
	m.patched_versions = nil
}

// SetSeverity sets the "severity" field.
func (m *VulnerabilityMutation) SetSeverity(s string) {
	m.severity = &s
}

// Severity returns the value of the "severity" field in the mutation.
func (m *VulnerabilityMutation) Severity() (r string, exists bool) {
	v := m.severity
	if v == nil {
		return
	}
	return *v, true
}

// OldSeverity returns the old "severity" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldSeverity(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSeverity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSeverity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSeverity: %w", err)
	}
	return oldValue.Severity, nil
}

// ResetSeverity resets all changes to the "severity" field.
func (m *VulnerabilityMutation) ResetSeverity() {
	m.severity = nil
}

// SetPiplineID sets the "pipline_id" field.
func (m *VulnerabilityMutation) SetPiplineID(s string) {
	m.pipline_id = &s
}

// PiplineID returns the value of the "pipline_id" field in the mutation.
func (m *VulnerabilityMutation) PiplineID() (r string, exists bool) {
	v := m.pipline_id
	if v == nil {
		return
	}
	return *v, true
}

// OldPiplineID returns the old "pipline_id" field's value of the Vulnerability entity.
// If the Vulnerability object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *VulnerabilityMutation) OldPiplineID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPiplineID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPiplineID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPiplineID: %w", err)
	}
	return oldValue.PiplineID, nil
}

// ResetPiplineID resets all changes to the "pipline_id" field.
func (m *VulnerabilityMutation) ResetPiplineID() {
	m.pipline_id = nil
}

// Where appends a list predicates to the VulnerabilityMutation builder.
func (m *VulnerabilityMutation) Where(ps ...predicate.Vulnerability) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the VulnerabilityMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *VulnerabilityMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Vulnerability, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *VulnerabilityMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *VulnerabilityMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Vulnerability).
func (m *VulnerabilityMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *VulnerabilityMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.name != nil {
		fields = append(fields, vulnerability.FieldName)
	}
	if m.summary != nil {
		fields = append(fields, vulnerability.FieldSummary)
	}
	if m._CVEID != nil {
		fields = append(fields, vulnerability.FieldCVEID)
	}
	if m.published_date != nil {
		fields = append(fields, vulnerability.FieldPublishedDate)
	}
	if m.last_modified != nil {
		fields = append(fields, vulnerability.FieldLastModified)
	}
	if m.description != nil {
		fields = append(fields, vulnerability.FieldDescription)
	}
	if m._NVD_score != nil {
		fields = append(fields, vulnerability.FieldNVDScore)
	}
	if m._CNA_score != nil {
		fields = append(fields, vulnerability.FieldCNAScore)
	}
	if m.affected_versions != nil {
		fields = append(fields, vulnerability.FieldAffectedVersions)
	}
	if m.patched_versions != nil {
		fields = append(fields, vulnerability.FieldPatchedVersions)
	}
	if m.severity != nil {
		fields = append(fields, vulnerability.FieldSeverity)
	}
	if m.pipline_id != nil {
		fields = append(fields, vulnerability.FieldPiplineID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *VulnerabilityMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case vulnerability.FieldName:
		return m.Name()
	case vulnerability.FieldSummary:
		return m.Summary()
	case vulnerability.FieldCVEID:
		return m.CVEID()
	case vulnerability.FieldPublishedDate:
		return m.PublishedDate()
	case vulnerability.FieldLastModified:
		return m.LastModified()
	case vulnerability.FieldDescription:
		return m.Description()
	case vulnerability.FieldNVDScore:
		return m.NVDScore()
	case vulnerability.FieldCNAScore:
		return m.CNAScore()
	case vulnerability.FieldAffectedVersions:
		return m.AffectedVersions()
	case vulnerability.FieldPatchedVersions:
		return m.PatchedVersions()
	case vulnerability.FieldSeverity:
		return m.Severity()
	case vulnerability.FieldPiplineID:
		return m.PiplineID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *VulnerabilityMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case vulnerability.FieldName:
		return m.OldName(ctx)
	case vulnerability.FieldSummary:
		return m.OldSummary(ctx)
	case vulnerability.FieldCVEID:
		return m.OldCVEID(ctx)
	case vulnerability.FieldPublishedDate:
		return m.OldPublishedDate(ctx)
	case vulnerability.FieldLastModified:
		return m.OldLastModified(ctx)
	case vulnerability.FieldDescription:
		return m.OldDescription(ctx)
	case vulnerability.FieldNVDScore:
		return m.OldNVDScore(ctx)
	case vulnerability.FieldCNAScore:
		return m.OldCNAScore(ctx)
	case vulnerability.FieldAffectedVersions:
		return m.OldAffectedVersions(ctx)
	case vulnerability.FieldPatchedVersions:
		return m.OldPatchedVersions(ctx)
	case vulnerability.FieldSeverity:
		return m.OldSeverity(ctx)
	case vulnerability.FieldPiplineID:
		return m.OldPiplineID(ctx)
	}
	return nil, fmt.Errorf("unknown Vulnerability field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VulnerabilityMutation) SetField(name string, value ent.Value) error {
	switch name {
	case vulnerability.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case vulnerability.FieldSummary:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSummary(v)
		return nil
	case vulnerability.FieldCVEID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCVEID(v)
		return nil
	case vulnerability.FieldPublishedDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublishedDate(v)
		return nil
	case vulnerability.FieldLastModified:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastModified(v)
		return nil
	case vulnerability.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case vulnerability.FieldNVDScore:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNVDScore(v)
		return nil
	case vulnerability.FieldCNAScore:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCNAScore(v)
		return nil
	case vulnerability.FieldAffectedVersions:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAffectedVersions(v)
		return nil
	case vulnerability.FieldPatchedVersions:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPatchedVersions(v)
		return nil
	case vulnerability.FieldSeverity:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSeverity(v)
		return nil
	case vulnerability.FieldPiplineID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPiplineID(v)
		return nil
	}
	return fmt.Errorf("unknown Vulnerability field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *VulnerabilityMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *VulnerabilityMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *VulnerabilityMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Vulnerability numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *VulnerabilityMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *VulnerabilityMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *VulnerabilityMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Vulnerability nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *VulnerabilityMutation) ResetField(name string) error {
	switch name {
	case vulnerability.FieldName:
		m.ResetName()
		return nil
	case vulnerability.FieldSummary:
		m.ResetSummary()
		return nil
	case vulnerability.FieldCVEID:
		m.ResetCVEID()
		return nil
	case vulnerability.FieldPublishedDate:
		m.ResetPublishedDate()
		return nil
	case vulnerability.FieldLastModified:
		m.ResetLastModified()
		return nil
	case vulnerability.FieldDescription:
		m.ResetDescription()
		return nil
	case vulnerability.FieldNVDScore:
		m.ResetNVDScore()
		return nil
	case vulnerability.FieldCNAScore:
		m.ResetCNAScore()
		return nil
	case vulnerability.FieldAffectedVersions:
		m.ResetAffectedVersions()
		return nil
	case vulnerability.FieldPatchedVersions:
		m.ResetPatchedVersions()
		return nil
	case vulnerability.FieldSeverity:
		m.ResetSeverity()
		return nil
	case vulnerability.FieldPiplineID:
		m.ResetPiplineID()
		return nil
	}
	return fmt.Errorf("unknown Vulnerability field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *VulnerabilityMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *VulnerabilityMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *VulnerabilityMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *VulnerabilityMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *VulnerabilityMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *VulnerabilityMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *VulnerabilityMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Vulnerability unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *VulnerabilityMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Vulnerability edge %s", name)
}
