// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Vulnerability is the predicate function for vulnerability builders.
type Vulnerability func(*sql.Selector)
